name: project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  convex_bottom_bar: ^3.2.0
  awesome_dialog: ^3.2.1
  file_picker: ^8.0.5
  pdf_render: ^1.4.10
  flutter_pdfview: ^1.3.2
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    # - assets/logo.png
  uses-material-design: true
